/*
    This file is a part of MapMe.

    MapMe is a free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/*!
 * \file options.h
 * \brief MapMe options.
 * \author Emeric GRANGE <emeric.grange@gmail.com>
 * \date 2011
 *
 * Some defines generated by cmake end ups in this file.
 * /!\ DO NOT EDIT THIS FILE /!\
 * Every changes made here will be overwrited by cmake!
 */

#ifndef CONFIG_H
#define CONFIG_H
/* ************************************************************************** */

#define MapMe_VERSION_MAJOR 0
#define MapMe_VERSION_MINOR 2

#define ENABLE_DEBUG   1 //!< Toggle debug output
#define ENABLE_COLORS  1 //!< Toggle colored console output
#define ENABLE_STDINT  0 //!< Toggle C99 STD INT support

/* ************************************************************************** */
#endif // CONFIG_H
